### ISSUE TITLE
Announcement on Julia Discourse

### ISSUE THREAD

**Issue by dillondaudert** [mrazomej/AutoEncode.jl#12]
Hello,

This package looks very exciting - have you considered making an announcement on the Julia [Discourse](https://discourse.julialang.org/c/package-announcements/60) to increase visibility?

**Comment by mrazomej** [comment]
Hey @dillondaudert, thank you so much! I didn't think about it before, but I agree that I should post something on the discourse. I wonder if I should wait for the [JOSS reviews](https://github.com/openjournals/joss-reviews/issues/6794) to finish before posting something.

**Comment by dillondaudert** [comment]
Myself, I'd make an announcement as soon as I felt comfortable with the implementation and functionality, and wanted people to use the package. I wouldn't worry about waiting for the publication.

**Comment by mrazomej** [comment]
That makes perfect sense. Thanks for the advice. I'll prepare the announcement!
