### ISSUE TITLE
[JOSS Submission Review]: Automated Tests Failing for the Package

### ISSUE THREAD

**Issue by sandeshkatakam** [mrazomej/AutoEncode.jl#13]
I added the package locally and tried executing automated testing using (test AutoEncoderToolkit) and I am getting some errors even tho most of the tests passed. Is there any explanation for the same?

I am attaching the screenshots of the test summary below:
![Auomatedtestfailreport](https://github.com/mrazomej/AutoEncoderToolkit.jl/assets/88609382/4e458c89-bc06-40d1-858c-6528fcb553f5)
![JOSSReviewautomatedtestfail1](https://github.com/mrazomej/AutoEncoderToolkit.jl/assets/88609382/8c331c99-67e3-4662-aa9b-62345006d7df)

**Comment by mrazomej** [comment]
@sandeshkatakam, I just downloaded the package on a different computer from the one I used to code it, and all tests passed.

```julia
All tests passed!

Test Summary:         | Pass  Total     Time
AutoEncoderToolkit.jl | 1387   1387  2m48.5s
```

Could you provide more information on the error messages you are getting?

**Comment by sandeshkatakam** [comment]
Actually It worked fine! I tested it again with fresh installation of the package. Thank you! And sorry for the delayed response from my side
